name: update-page

on:
  push:
    branches:
      - 'master'
    paths:
      - 'translated-docs/**'
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook-update-action

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: build
        run: |
          sudo apt update
          sudo pip3 install setuptools
          sudo pip3 install -r translated-docs/requirements.txt
          rm -rf docs/
          sphinx-build -b html translated-docs docs -E
          cd docs/
          touch .nojekyll
          rm -rf .doctrees/
          rm -rf _sources/
      - name: commit changes
        run: |
          git config --global credential.helper store
          git config --global user.email "bot@luatos.com"
          git config --global user.name "luatos_bot"
          git add .
          git commit -m "ci auto update docs"
        continue-on-error: true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

