name: update-page

on:
  push:
    paths:
      - 'translated-docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: build
        run: |
          sudo apt update
          sudo pip3 install setuptools
          sudo pip3 install -r requirements.txt
          rm -rf docs/
          sphinx-build -b html translated-docs docs -E
          cd docs/
          echo "this is offline version, please visit wiki.luatos.com for latest version, document update on $(TZ=UTC-8 date +%Y-%m-%d,%H:%m:%S)" > "readme.txt"
          cd ..
          git add .
          git commit -m "ci auto update docs"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs
